import { motion } from "framer-motion";
import {
    FaLightbulb,
    FaArrowTrendUp,
    FaCircleInfo,
} from "react-icons/fa6";

function Suggestions({ analysis }) {
    const suggestions = analysis?.suggestions || [];

    return (
        <motion.div
            initial={{ opacity: 0, y: 25 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
            className="mt-10 overflow-hidden rounded-3xl bg-white shadow-lg"
        >
            {/* Header */}

            <div className="bg-gradient-to-r from-amber-500 to-orange-500 px-8 py-6 text-white">

                <div className="flex items-center gap-4">

                    <FaLightbulb className="text-4xl" />

                    <div>

                        <h2 className="text-3xl font-bold">
                            AI Suggestions
                        </h2>

                        <p className="mt-2 text-orange-100">
                            Personalized recommendations generated by AI to improve your resume.
                        </p>

                    </div>

                </div>

            </div>

            <div className="p-8">

                {suggestions.length > 0 ? (

                    <div className="space-y-5">

                        {suggestions.map((suggestion, index) => (

                            <motion.div
                                key={index}
                                initial={{ opacity: 0, y: 20 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{
                                    delay: index * 0.08,
                                }}
                                whileHover={{
                                    y: -3,
                                }}
                                className="rounded-2xl border border-orange-100 bg-orange-50 p-6 transition hover:shadow-md"
                            >

                                <div className="flex items-start gap-5">

                                    <div className="rounded-xl bg-orange-100 p-3">

                                        <FaArrowTrendUp className="text-xl text-orange-600" />

                                    </div>

                                    <div className="flex-1">

                                        <div className="mb-3 flex items-center justify-between">

                                            <h3 className="font-semibold text-slate-800">
                                                Recommendation #{index + 1}
                                            </h3>

                                            <span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-semibold text-orange-700">
                                                Suggested
                                            </span>

                                        </div>

                                        <p className="leading-7 text-slate-600">
                                            {suggestion}
                                        </p>

                                    </div>

                                </div>

                            </motion.div>

                        ))}

                    </div>

                ) : (

                    <div className="rounded-3xl bg-slate-50 p-10 text-center">

                        <FaCircleInfo className="mx-auto mb-4 text-5xl text-slate-300" />

                        <h3 className="text-xl font-semibold text-slate-600">
                            No AI Suggestions Available
                        </h3>

                        <p className="mt-2 text-slate-500">
                            Upload and analyze your resume to receive personalized ATS improvement suggestions.
                        </p>

                    </div>

                )}

            </div>

        </motion.div>
    );
}

export default Suggestions;